# Generated by Django 5.2.10 on 2026-01-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="mp_payment_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="mp_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
