# Generated by Django 5.2.10 on 2026-01-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_order_mp_payment_id_order_mp_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="mercadopago_payment_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
